### ISSUE TITLE
date missing for journal article in CFF output

### ISSUE THREAD

**Issue by egonw** [citation-js/plugin-software-formats#13]
On https://scholia.toolforge.org/work/Q28842753/export and the problem seems to be that the output is not for a journal article but for software?

![image](https://user-images.githubusercontent.com/26721/177091343-c443bf92-571c-41c8-b3a5-7863fce30a20.png)

**Comment by egonw** [comment]
Not urgent.

**Comment by larsgw** [comment]
The top level entry in a CFF file _has_ to be `dataset` or `software` so this is a bit difficult to handle. Scholia could set the entry as `preferred` instead of `main` if it is not one of those types, but then it is unclear which information should be put in the top-level entry.

**Comment by egonw** [comment]
Yeah, I was wondering if for articles it should not be outputted as 1.2.0 and `preferred-citation`:

```yaml
cff-version: 1.2.0
message: "If you use this software, please cite the WikiPathways RDF paper."
title: libGPML export library for GPMLRDF and WPRDF
url: "https://github.com/egonw/org.pathvisio.io.rdf"
preferred-citation:
  type: article
  title: "Using the Semantic Web for Rapid Integration of WikiPathways with Other Biological Online Data Resources"
  authors:
  - family-names: Waagmeester
    given-names: Andra
  - family-names: Summer-Kutmon
```

**Comment by larsgw** [comment]
I'm not sure I follow. How would you reliably retrieve the name and repository from the article in this example?

**Comment by egonw** [comment]
This was just a copy/paste... indeed you don't have that info, so the better template is:

```
cff-version: 1.2.0
message: "If you use this, please cite the prefered citation."
preferred-citation:
  type: article
  title: "Using the Semantic Web for Rapid Integration of WikiPathways with Other Biological Online Data Resources"
  authors:
  - family-names: Waagmeester
    given-names: Andra
  - family-names: Summer-Kutmon
```
